projects:
  homework_03:
    path: homework_03
  morning_glitter: {}
  snowy_echo: {}
  unit_0_setup: {}
  unit_1_data_preparation:
    path: unit_1_data_preparation
  unit_2_training: {}
  unit_3_observability: {}
